def pipeline_version = VersionNumber(versionNumberString: '${BUILD_DATE_FORMATTED,"yyyyMMdd"}.${BUILDS_TODAY_Z}')
def kernelci_arches = ["arm64"] //, "armel", "x86", "x86_64"]
def debian_arches = ["arm64", "armhf", "i386", "amd64"]
def toolchain_arches = ["aarch64-linux-gnu", "arm-linux-gnueabihf", "i386-linux-gnu", "x86_64-linux-gnu"]

def makeImageStep(String pipeline_version, String kernelci_arch, String debian_arch) {
  return {
    node("docker-slave") {
      stage("Checkout") {
        checkout scm
      }

      docker.build("debian", "-f jenkins/debian/Dockerfile_debos --pull .").inside("--device=/dev/kvm") {
        stage("Build base image for ${kernelci_arch}") {
          sh "debos -t architecture:${debian_arch} -t basename:${pipeline_version}/${kernelci_arch}/ -t extra_packages:'libpciaccess0 libkmod2 libprocps6 libcairo2 libunwind8 libudev1' jenkins/debian/debos/stretch.yaml"
          stash includes: "${pipeline_version}/${kernelci_arch}/rootfs.cpio.gz", name: 'rootfs'
        }
      }
    }
  }
}

def makeBuildStep(String pipeline_version, String kernelci_arch, String debian_arch) {
  return {
    node("docker-slave") {
      stage("Checkout") {
        checkout scm
      }

      docker.build("debian", "-f jenkins/debian/Dockerfile_debian --pull .").inside("--device=/dev/kvm") {
        dir("${PIPELINE_VERSION}") {
          dir("libdrm") {
            stage("Build libdrm for ${kernelci_arch}") {
              git url: 'git://anongit.freedesktop.org/mesa/drm'
              sh "mkdir build"
              sh 'PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig/ sh autogen.sh --host=arm-linux-gnueabihf --enable-intel --prefix=$(pwd)/build/'
              sh 'make -j$(nproc) V=1'
              sh 'make -j$(nproc) install V=1'
              sh 'tar cvfz libdrm-build.tar.gz build/'
              stash includes: "libdrm-build.tar.gz", name: 'libdrm-build'
            }
          }

          dir("igt-gpu-tools") {
            stage("Build igt for ${kernelci_arch}") {
              git url: 'git://anongit.freedesktop.org/drm/igt-gpu-tools'
              sh 'PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig/:$(pwd)/../libdrm/build/lib/pkgconfig sh autogen.sh --host=arm-linux-gnueabihf'
              sh 'make -j$(nproc) V=1'
              sh 'tar cvfz igt-build.tar.gz tests/core_auth tests/core_get_client_auth tests/core_getclient tests/core_getstats tests/core_getversion tests/core_prop_blob tests/core_setmaster_vs_auth tests/drm_read tests/kms_addfb_basic tests/kms_atomic tests/kms_flip_event_leak tests/kms_setmode tests/kms_vblank tests/kms_frontbuffer_tracking tests/kms_flip tests/testdisplay'
              stash includes: "igt-build.tar.gz", name: 'igt-build'
            }
          }
        }
      }
    }
  }
}

def stepsForParallel = [:]
for (int i = 0; i < kernelci_arches.size(); i++) {
    def s = kernelci_arches.get(i)
    def buildStep = "Build image for ${s}"
    stepsForParallel[buildStep] = makeImageStep(pipeline_version,
                                                kernelci_arches.get(i),
                                                debian_arches.get(i))
    buildStep = "Build test suite for ${s}"
    stepsForParallel[buildStep] = makeBuildStep(pipeline_version,
                                                kernelci_arches.get(i),
                                                debian_arches.get(i))
}

parallel stepsForParallel
